# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  MATHWORKS_SKIP_ACTIVATION: true

pool:
  vmImage: ubuntu-latest

steps:
- task: InstallMATLAB@0
  inputs:
    release: R2023a
- task: RunMATLABTests@0
  inputs:
    testResultsSimulinkTest: test-results/results.mldatx
    modelCoverageCobertura: model-coverage/coverage.xml
  env:
    MATHWORKS_TOKEN: $(MATHWORKS_TOKEN)
    MATHWORKS_ACCOUNT: $(MATHWORKS_ACCOUNT)
- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  inputs:
    pathToPublish: test-results/results.mldatx
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: test-results/results.mldatx

- task: PublishCodeCoverageResults@1
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: model-coverage/coverage.xml